name: Production deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-lambda:
    name: Auto deploy to AWS Lambda
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Dependencies
        run: |
          cd server
          npm install -g serverless
          yarn install

      - name: Deploy to Lambda
        run: |
          cd server
          sls deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
